### ISSUE TITLE
Follower removed during relic carrying.

### ISSUE THREAD

**Issue by indieus** [jwiggins/ggj2016#59]

**Comment by indieus** [comment]
If one of the paths is removed from an intersection that contains the relic, the relic should still be picked up by the other existing path.

**Comment by jwiggins** [comment]
Here's what's happening. When you remove an `Adherent` and its path, all the path intersections are cleared and refreshed. If the relic is sitting at a spot on a `Path` which was an intersection but now is not an intersection then this code doesn't get triggered when the `Adherent` passes the relic:
https://github.com/jwiggins/ggj2016/blob/master/Automata/Assets/Scripts/Adherent.cs#L29-L33
